"""ClusterProfiler: statistical + narrative characterization of discovered clusters."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Dict, List, Optional

import pandas as pd
from scipy.stats import chi2_contingency, mannwhitneyu

from .models import ClusterReport

logger = logging.getLogger(__name__)

_TOP_N_FEATURES = 3  # features to highlight in narrative


class ClusterProfiler:
    """Characterize clusters with statistics and rule-based clinical narratives.

    No LLM is used.  Narratives are generated by comparing each cluster's
    feature means to the global mean.

    Args:
        target_col: Binary outcome column (e.g. ``"heart_disease"``).
    """

    def __init__(self, target_col: str = "heart_disease") -> None:
        self.target_col = target_col

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def compute(
        self,
        df: pd.DataFrame,
        cluster_col: str = "group_cluster",
        feature_cols: Optional[List[str]] = None,
    ) -> ClusterReport:
        """Compute statistics and narratives for all clusters.

        Args:
            df: DataFrame with cluster assignment, features, and target column.
            cluster_col: Name of the cluster column.
            feature_cols: Numeric feature columns to profile.  Defaults to all
                numeric columns excluding *cluster_col* and *target_col*.

        Returns:
            :class:`ClusterReport` with feature means/stds, chi-square,
            Mann-Whitney U results, narratives, and outcome rates.
        """
        cols = self._resolve_cols(df, cluster_col, feature_cols)
        cluster_ids = sorted(df[cluster_col].dropna().unique())

        global_means = df[cols].mean()
        feature_means = df.groupby(cluster_col)[cols].mean()
        feature_stds = df.groupby(cluster_col)[cols].std()

        outcome_rates = pd.Series(dtype=float)
        if self.target_col in df.columns:
            outcome_rates = df.groupby(cluster_col)[self.target_col].mean()

        chi_results = self._chi_square_test(df, cluster_col)
        mw_results = self._mann_whitney_u(df, cluster_col, cluster_ids)
        narratives = self._build_narratives(feature_means, global_means, cluster_ids)

        return ClusterReport(
            feature_means=feature_means,
            feature_stds=feature_stds,
            global_means=global_means,
            chi_square_results=chi_results,
            mann_whitney_results=mw_results,
            narratives=narratives,
            outcome_rates=outcome_rates,
        )

    def save_report(self, report: ClusterReport, output_file: Path) -> Path:
        """Write a Markdown report to *output_file*."""
        output_file.parent.mkdir(parents=True, exist_ok=True)
        lines = ["# Cluster Subgroup Profiles\n"]

        # -- Narratives
        lines.append("## Clinical Narratives\n")
        for cid, narrative in sorted(report.narratives.items()):
            rate_str = ""
            if cid in report.outcome_rates.index:
                rate = report.outcome_rates[cid]
                rate_str = f" (outcome rate: {rate:.1%})"
            lines.append(f"- **Cluster {cid}**{rate_str}: {narrative}")
        lines.append("")

        # -- Feature means table
        lines.append("## Feature Means by Cluster\n")
        lines.append(report.feature_means.round(3).to_markdown())
        lines.append("")

        # -- Chi-square
        if report.chi_square_results:
            lines.append("## Cluster vs Outcome Independence (Chi-Square)\n")
            lines.append(pd.DataFrame(report.chi_square_results).round(4).to_markdown(index=False))
            lines.append("")

        # -- Mann-Whitney U
        if report.mann_whitney_results:
            lines.append("## Pairwise Outcome Distribution (Mann-Whitney U)\n")
            lines.append(
                pd.DataFrame(report.mann_whitney_results).round(4).to_markdown(index=False)
            )
            lines.append("")

        output_file.write_text("\n".join(lines))
        logger.info("[SUCCESS] subgroup_profiles saved to %s", output_file)
        return output_file

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _resolve_cols(
        self, df: pd.DataFrame, cluster_col: str, feature_cols: Optional[List[str]]
    ) -> List[str]:
        if feature_cols is not None:
            return [c for c in feature_cols if c in df.columns]
        exclude = {cluster_col, self.target_col}
        return [c for c in df.select_dtypes(include="number").columns if c not in exclude]

    def _chi_square_test(self, df: pd.DataFrame, cluster_col: str) -> List[Dict]:
        """Chi-square test: cluster assignment vs binary outcome."""
        if self.target_col not in df.columns:
            return []
        try:
            contingency = pd.crosstab(df[cluster_col], df[self.target_col])
            chi2, p_value, dof, _ = chi2_contingency(contingency)
            return [
                {
                    "test": "chi_square",
                    "variable_1": cluster_col,
                    "variable_2": self.target_col,
                    "chi2_stat": chi2,
                    "p_value": p_value,
                    "dof": dof,
                    "significant": p_value < 0.05,
                }
            ]
        except Exception as exc:
            logger.debug("chi_square_test failed: %s", exc)
            return []

    def _mann_whitney_u(self, df: pd.DataFrame, cluster_col: str, cluster_ids: List) -> List[Dict]:
        """Pairwise Mann-Whitney U: compare outcome distributions between clusters."""
        if self.target_col not in df.columns:
            return []
        results = []
        for i, c1 in enumerate(cluster_ids):
            for c2 in cluster_ids[i + 1 :]:
                g1 = df[df[cluster_col] == c1][self.target_col].dropna()
                g2 = df[df[cluster_col] == c2][self.target_col].dropna()
                if len(g1) < 2 or len(g2) < 2:
                    continue
                try:
                    stat, p_value = mannwhitneyu(g1, g2, alternative="two-sided")
                    results.append(
                        {
                            "cluster_a": int(c1),
                            "cluster_b": int(c2),
                            "u_stat": stat,
                            "p_value": p_value,
                            "significant": p_value < 0.05,
                        }
                    )
                except Exception as exc:
                    logger.debug("mann_whitney c%s vs c%s: %s", c1, c2, exc)
        return results

    def _build_narratives(
        self,
        feature_means: pd.DataFrame,
        global_means: pd.Series,
        cluster_ids: List,
    ) -> Dict[int, str]:
        narratives = {}
        for cid in cluster_ids:
            if cid not in feature_means.index:
                narratives[int(cid)] = "No data."
                continue
            row = feature_means.loc[cid]
            delta = (row - global_means).dropna()
            if delta.empty:
                narratives[int(cid)] = "No features available."
                continue
            # Top features with highest absolute deviation from global mean
            top = delta.abs().nlargest(_TOP_N_FEATURES)
            parts = []
            for feat in top.index:
                d = delta[feat]
                direction = "elevated" if d > 0 else "lower"
                parts.append(
                    f"{feat} {direction} ({row[feat]:.2f} vs {global_means[feat]:.2f} global)"
                )
            narratives[int(cid)] = "Cluster %d: %s." % (int(cid), "; ".join(parts))
        return narratives
