"""Pipeline orchestration utilities — stage definitions, checkpointing, and flow control."""

from fairxai.pipeline.stages import (
    CARDIAC_STAGE_BY_NAME,
    CARDIAC_STAGE_BY_NUMBER,
    CARDIAC_STAGES,
    DERMATOLOGY_STAGE_BY_NAME,
    DERMATOLOGY_STAGE_BY_NUMBER,
    DERMATOLOGY_STAGES,
    PIPELINE_STAGES,
    STAGE_BY_NAME,
    STAGE_BY_NUMBER,
    STAGES,
    PipelineStage,
    get_completed_stages,
    get_stage_range,
    get_stages,
    mark_stage_complete,
    resolve_stage,
    validate_prior_stages,
)

__all__ = [
    "STAGES",
    "CARDIAC_STAGES",
    "DERMATOLOGY_STAGES",
    "PIPELINE_STAGES",
    "STAGE_BY_NAME",
    "STAGE_BY_NUMBER",
    "CARDIAC_STAGE_BY_NAME",
    "CARDIAC_STAGE_BY_NUMBER",
    "DERMATOLOGY_STAGE_BY_NAME",
    "DERMATOLOGY_STAGE_BY_NUMBER",
    "PipelineStage",
    "get_stages",
    "resolve_stage",
    "get_stage_range",
    "validate_prior_stages",
    "mark_stage_complete",
    "get_completed_stages",
]
